<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="5801" started-at="2018-03-01T18:18:48Z" finished-at="2018-03-01T18:18:54Z">
    <groups>
    </groups>
    <test name="First Test" duration-ms="5801" started-at="2018-03-01T18:18:48Z" finished-at="2018-03-01T18:18:54Z">
      <class name="com.packt.tests.FirstTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.packt.tests.FirstTest@7006c658]" name="setUp" is-config="true" duration-ms="3277" started-at="2018-03-01T13:18:48Z" finished-at="2018-03-01T13:18:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="firstTest()[pri:0, instance:com.packt.tests.FirstTest@7006c658]" name="firstTest" duration-ms="1811" started-at="2018-03-01T13:18:51Z" finished-at="2018-03-01T13:18:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
LogOut button is not displayed., Page source doesn't contain expected text: 'You logged into a secure area!']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
LogOut button is not displayed., Page source doesn't contain expected text: 'You logged into a secure area!'
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.packt.tests.FirstTest.firstTest(FirstTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.FirstTest@7006c658]" name="tearDown" is-config="true" duration-ms="695" started-at="2018-03-01T13:18:53Z" finished-at="2018-03-01T13:18:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.packt.tests.FirstTest -->
    </test> <!-- First Test -->
  </suite> <!-- Suite1 -->
</testng-results>
